In [1]:
import numpy as np

# hello_numpy
## 初始numpy

In [8]:
score = np.array(
[[80, 89, 86, 67, 79],
[78, 97, 89, 67, 81],
[90, 94, 78, 67, 74],
[91, 91, 90, 67, 69],
[76, 87, 75, 67, 86],
[70, 79, 84, 67, 84],
[94, 92, 93, 67, 64],
[86, 85, 83, 67, 80]])
score

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

## ndarray和原生Python效率对比

In [9]:
import random
import time
import numpy as np
a = []
for i in range(1000):
    a.append(random.random())
    
# 通过%time魔法⽅法, 查看当前⾏的代码运⾏⼀次所花费的时间
%time sum1=sum(a)

b=np.array(a)

%time sum2=np.sum(b)

CPU times: user 12 µs, sys: 9 µs, total: 21 µs
Wall time: 26.2 µs
CPU times: user 41 µs, sys: 32 µs, total: 73 µs
Wall time: 77.7 µs


# ndarra的使用
## 数组的属性

In [10]:
score

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

In [11]:
score.shape

(8, 5)

In [13]:
score.ndim

2

In [14]:
score.size

40

In [15]:
score.itemsize

8

In [16]:
score.dtype

dtype('int64')

## 数组的形状

In [20]:
a = np.array([1,2,3])

In [21]:
a

array([1, 2, 3])

In [23]:
a.shape

(3,)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])