In [1]:
import numpy as np

# 逻辑运算

In [2]:
score = np.random.randint(40, 100, (10, 5))
score

array([[77, 95, 52, 68, 54],
       [51, 66, 40, 40, 61],
       [89, 82, 96, 55, 53],
       [98, 40, 74, 44, 97],
       [45, 47, 67, 67, 75],
       [76, 47, 83, 60, 97],
       [67, 54, 89, 82, 45],
       [76, 53, 90, 54, 94],
       [63, 54, 42, 97, 61],
       [97, 84, 57, 88, 42]])

In [3]:
test_score = score[6:, 0:5]
test_score

array([[67, 54, 89, 82, 45],
       [76, 53, 90, 54, 94],
       [63, 54, 42, 97, 61],
       [97, 84, 57, 88, 42]])

In [4]:
test_score > 60

array([[ True, False,  True,  True, False],
       [ True, False,  True, False,  True],
       [ True, False, False,  True,  True],
       [ True,  True, False,  True, False]])

In [5]:
test_score[test_score > 60] = 1
test_score

array([[ 1, 54,  1,  1, 45],
       [ 1, 53,  1, 54,  1],
       [ 1, 54, 42,  1,  1],
       [ 1,  1, 57,  1, 42]])

# 通⽤判断函数

In [6]:
np.all(score[0:2, :] > 60)

False

In [7]:
score

array([[77, 95, 52, 68, 54],
       [51, 66, 40, 40, 61],
       [89, 82, 96, 55, 53],
       [98, 40, 74, 44, 97],
       [45, 47, 67, 67, 75],
       [76, 47, 83, 60, 97],
       [ 1, 54,  1,  1, 45],
       [ 1, 53,  1, 54,  1],
       [ 1, 54, 42,  1,  1],
       [ 1,  1, 57,  1, 42]])

In [8]:
np.any(score[0:2, :] > 90)

True

# np.where(三元运算符)

In [9]:
temp = score[:4, :4]
temp

array([[77, 95, 52, 68],
       [51, 66, 40, 40],
       [89, 82, 96, 55],
       [98, 40, 74, 44]])

In [10]:
np.where(temp > 60, 1, 0)

array([[1, 1, 0, 1],
       [0, 1, 0, 0],
       [1, 1, 1, 0],
       [1, 0, 1, 0]])

In [11]:
np.where(np.logical_and(temp > 60, temp < 90), 1, 0)

array([[1, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 1, 0]])

In [12]:
np.where(np.logical_or(temp > 90, temp < 60), 1, 0)

array([[0, 1, 1, 0],
       [1, 0, 1, 1],
       [0, 0, 1, 1],
       [1, 1, 0, 1]])

# 统计运算

In [13]:
temp = score[:4, :]
temp

array([[77, 95, 52, 68, 54],
       [51, 66, 40, 40, 61],
       [89, 82, 96, 55, 53],
       [98, 40, 74, 44, 97]])

In [14]:
np.max(temp)

98

In [15]:
np.mean(temp)

66.6

In [16]:
np.max(temp, axis=0)

array([98, 95, 96, 68, 97])

In [17]:
np.max(temp, axis=1)

array([95, 66, 96, 98])

In [18]:
np.argmax(temp)

15

In [19]:
np.argmax(temp, axis=0)

array([3, 0, 2, 0, 3])

In [20]:
np.argmin(temp, axis=0)

array([1, 3, 1, 1, 2])

# 数组间运算

In [21]:
a = np.array([[1,2,3],[3,4,5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [22]:
a + 3

array([[4, 5, 6],
       [6, 7, 8]])

In [23]:
a / 2

array([[0.5, 1. , 1.5],
       [1.5, 2. , 2.5]])

In [24]:
a = [1,2,3]  #列表的运算
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [25]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])

In [26]:
# arr1 + arr2 # 不可以进行计算

In [27]:
arr1 = np.array([[0],[1],[2],[3]])
arr1.shape

(4, 1)

In [28]:
arr2 = np.array([1,2,3])
arr2.shape

(3,)

In [29]:
arr1 + arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [30]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1], [3]])

In [31]:
arr2 + arr1

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])

# 矩阵运算

In [32]:
a = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])
a

array([[80, 86],
       [82, 80],
       [85, 78],
       [90, 90],
       [86, 82],
       [82, 90],
       [78, 80],
       [92, 94]])

In [33]:
b = np.array([[0.7], [0.3]])
b

array([[0.7],
       [0.3]])

In [34]:
np.dot(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [35]:
np.matmul(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [36]:
c = 10

In [37]:
np.dot(a,c)

array([[800, 860],
       [820, 800],
       [850, 780],
       [900, 900],
       [860, 820],
       [820, 900],
       [780, 800],
       [920, 940]])

In [38]:
# np.matmul(a,c) # matmul不支持矩阵和标量的乘法