# Series
## serise的创建

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.Series(np.arange(9))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
dtype: int64

In [3]:
pd.Series([1.2, 2.3, 4.5, 5.0], index=[1,2,3,4])

1    1.2
2    2.3
3    4.5
4    5.0
dtype: float64

In [4]:
color_count = pd.Series({"red":10, "green":20, "blue":100})
color_count

red       10
green     20
blue     100
dtype: int64

## Series的属性

In [5]:
color_count.index

Index(['red', 'green', 'blue'], dtype='object')

In [6]:
color_count.values

array([ 10,  20, 100])

In [7]:
color_count[0]

10

In [8]:
color_count[1]

20

# DataFrame
## DataFrame的创建

In [9]:
pd.DataFrame(np.random.randn(2,3))

0         1         2
0  1.030295  0.881991  0.027700
1 -0.144948  1.969100  1.193789

In [10]:
score = np.random.randint(40,100,(10, 5))
score

array([[57, 57, 82, 55, 91],
       [44, 87, 71, 99, 55],
       [93, 88, 45, 89, 51],
       [42, 77, 51, 95, 86],
       [43, 58, 51, 77, 93],
       [95, 89, 64, 48, 40],
       [63, 87, 64, 60, 72],
       [90, 78, 44, 83, 65],
       [66, 43, 40, 68, 89],
       [81, 75, 76, 83, 51]])

In [11]:
score_df = pd.DataFrame(score)
score_df

0   1   2   3   4
0  57  57  82  55  91
1  44  87  71  99  55
2  93  88  45  89  51
3  42  77  51  95  86
4  43  58  51  77  93
5  95  89  64  48  40
6  63  87  64  60  72
7  90  78  44  83  65
8  66  43  40  68  89
9  81  75  76  83  51

In [12]:
subjects = ["语⽂", "数学", "英语", "政治", "体育"]
stu = ['同学' + str(i) for i in range (score.shape[0])]
data = pd.DataFrame(score, columns=subjects, index=stu)
data

语⽂  数学  英语  政治  体育
同学0  57  57  82  55  91
同学1  44  87  71  99  55
同学2  93  88  45  89  51
同学3  42  77  51  95  86
同学4  43  58  51  77  93
同学5  95  89  64  48  40
同学6  63  87  64  60  72
同学7  90  78  44  83  65
同学8  66  43  40  68  89
同学9  81  75  76  83  51

## DataFrame的属性

In [13]:
data.shape

(10, 5)

In [14]:
data.index

Index(['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9'], dtype='object')

In [15]:
data.columns

Index(['语⽂', '数学', '英语', '政治', '体育'], dtype='object')

In [16]:
data.values

array([[57, 57, 82, 55, 91],
       [44, 87, 71, 99, 55],
       [93, 88, 45, 89, 51],
       [42, 77, 51, 95, 86],
       [43, 58, 51, 77, 93],
       [95, 89, 64, 48, 40],
       [63, 87, 64, 60, 72],
       [90, 78, 44, 83, 65],
       [66, 43, 40, 68, 89],
       [81, 75, 76, 83, 51]])

In [17]:
data.T

同学0  同学1  同学2  同学3  同学4  同学5  同学6  同学7  同学8  同学9
语⽂   57   44   93   42   43   95   63   90   66   81
数学   57   87   88   77   58   89   87   78   43   75
英语   82   71   45   51   51   64   64   44   40   76
政治   55   99   89   95   77   48   60   83   68   83
体育   91   55   51   86   93   40   72   65   89   51

In [18]:
data.head()

语⽂  数学  英语  政治  体育
同学0  57  57  82  55  91
同学1  44  87  71  99  55
同学2  93  88  45  89  51
同学3  42  77  51  95  86
同学4  43  58  51  77  93

In [19]:
data.head(3)

语⽂  数学  英语  政治  体育
同学0  57  57  82  55  91
同学1  44  87  71  99  55
同学2  93  88  45  89  51

In [20]:
data.tail()

语⽂  数学  英语  政治  体育
同学5  95  89  64  48  40
同学6  63  87  64  60  72
同学7  90  78  44  83  65
同学8  66  43  40  68  89
同学9  81  75  76  83  51

In [21]:
data.tail(3)

语⽂  数学  英语  政治  体育
同学7  90  78  44  83  65
同学8  66  43  40  68  89
同学9  81  75  76  83  51

## DatatFrame索引的设置 

In [22]:
stu = ['同学_' + str(i) for i in range (score.shape[0])]
data.index = stu
data

语⽂  数学  英语  政治  体育
同学_0  57  57  82  55  91
同学_1  44  87  71  99  55
同学_2  93  88  45  89  51
同学_3  42  77  51  95  86
同学_4  43  58  51  77  93
同学_5  95  89  64  48  40
同学_6  63  87  64  60  72
同学_7  90  78  44  83  65
同学_8  66  43  40  68  89
同学_9  81  75  76  83  51

In [23]:
# data.index[2] = "同学__" # 不能单独修改

In [24]:
data.reset_index()

index  语⽂  数学  英语  政治  体育
0  同学_0  57  57  82  55  91
1  同学_1  44  87  71  99  55
2  同学_2  93  88  45  89  51
3  同学_3  42  77  51  95  86
4  同学_4  43  58  51  77  93
5  同学_5  95  89  64  48  40
6  同学_6  63  87  64  60  72
7  同学_7  90  78  44  83  65
8  同学_8  66  43  40  68  89
9  同学_9  81  75  76  83  51

In [25]:
data.reset_index(drop=True)

语⽂  数学  英语  政治  体育
0  57  57  82  55  91
1  44  87  71  99  55
2  93  88  45  89  51
3  42  77  51  95  86
4  43  58  51  77  93
5  95  89  64  48  40
6  63  87  64  60  72
7  90  78  44  83  65
8  66  43  40  68  89
9  81  75  76  83  51

In [26]:
df = pd.DataFrame({'month': [1, 4, 7, 10],
'year': [2012, 2014, 2013, 2014],
'sale':[55, 40, 84, 31]})
df

month  year  sale
0      1  2012    55
1      4  2014    40
2      7  2013    84
3     10  2014    31

In [27]:
df.set_index("year")

month  sale
year             
2012      1    55
2014      4    40
2013      7    84
2014     10    31

In [33]:
df = df.set_index(['year','month'])

# MultiIndex与Panel
## MultiIndex

In [34]:
df

sale
year month      
2012 1        55
2014 4        40
2013 7        84
2014 10       31

In [35]:
df.index

MultiIndex([(2012,  1),
            (2014,  4),
            (2013,  7),
            (2014, 10)],
           names=['year', 'month'])

In [36]:
df.index.names

FrozenList(['year', 'month'])

In [37]:
df.index.levels

FrozenList([[2012, 2013, 2014], [1, 4, 7, 10]])

In [39]:
arrays = [[1, 1, 2, 2], ['red', 'blue', 'red', 'blue']]

In [41]:
pd.MultiIndex.from_arrays(arrays, names=('number', 'color'))

MultiIndex([(1,  'red'),
            (1, 'blue'),
            (2,  'red'),
            (2, 'blue')],
           names=['number', 'color'])

## Panel

In [51]:
p = pd.Panel(data=np.arange(24).reshape(4,3,2),
                items=list('ABCD'),
                major_axis=pd.date_range('20130101', periods=3),
                minor_axis=['first', 'second'])

AttributeError: module 'pandas' has no attribute 'Panel'